In [5]:
import numpy as np

In [6]:
x = np.array([1,2,3])
print(x)

x[0] = 100;
print(x)

[1 2 3]
[100   2   3]


In [7]:
y = np.arange(10)
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
y = np.arange(5,15)
print(y)

[ 5  6  7  8  9 10 11 12 13 14]


In [9]:
a = np.array([1,2,3,4,5])
# 메모리 주소를 복사
b = a;
print('a= '+str(a) + ' b=' + str(b))

a[0] = 100
print('a= '+str(a) + ' b=' + str(b))

a= [1 2 3 4 5] b=[1 2 3 4 5]
a= [100   2   3   4   5] b=[100   2   3   4   5]


In [10]:
a = np.array([1,2,3,4,5])
# a의 값을 복사
b = a.copy()
print('a= '+str(a) + ' b=' + str(b))

a[0] = 100
print('a= '+str(a) + ' b=' + str(b))

a= [1 2 3 4 5] b=[1 2 3 4 5]
a= [100   2   3   4   5] b=[1 2 3 4 5]


In [11]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([np.arange(1,4),np.arange(4,7)])
print(str(x) + '   shape :'+str(x.shape)+'\n')
print(str(y) + '   shape :'+str(y.shape)+'\n')
print('typeof(shape) :'+str(type(x.shape)))

[[1 2 3]
 [4 5 6]]   shape :(2, 3)

[[1 2 3]
 [4 5 6]]   shape :(2, 3)

typeof(shape) :<class 'tuple'>


In [12]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

w, h = x.shape
print(w)
print(h)

[[1 2 3]
 [4 5 6]]
2
3


In [13]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

print(x[0,0])
print(x[1,1])

x[0,0] = 100
print(x)

print(x[1,1])
print(x[1][1])

[[1 2 3]
 [4 5 6]]
1
5
[[100   2   3]
 [  4   5   6]]
5
5


In [14]:
x = np.zeros(2)
print(x)

[0. 0.]


In [15]:
y = np.zeros((2,2))
print(y)

[[0. 0.]
 [0. 0.]]


In [16]:
z = np.zeros((2,2,2))
print(z)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [17]:
x = np.ones(2)
print(x)

[1. 1.]


In [18]:
y = np.ones((2,2))
print(y)

[[1. 1.]
 [1. 1.]]


In [19]:
x = np.random.rand(5)
print(x)

[0.85423966 0.00328811 0.19526953 0.33640383 0.12103786]


In [20]:
y = np.random.rand(5,2)
print(y)

[[0.59224187 0.11006629]
 [0.59918573 0.09435317]
 [0.58762921 0.12898511]
 [0.88598154 0.70815324]
 [0.98550245 0.49911304]]


In [21]:
a = np.array([1,2,3,4])
b = a.reshape(2,2)   #마찬가지로 메모리 주소 복사

print(a)
print(b)
print(a.shape)
print(b.shape)

[1 2 3 4]
[[1 2]
 [3 4]]
(4,)
(2, 2)


In [22]:
a[0] = 50
print(a)
print(b)

[50  2  3  4]
[[50  2]
 [ 3  4]]


In [23]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print('x=' + str(x))
print('y=' + str(y))

x=[[1 2]
 [3 4]]
y=[[5 6]
 [7 8]]


In [24]:
print(x+y)

[[ 6  8]
 [10 12]]


In [25]:
print(x-y)

[[-4 -4]
 [-4 -4]]


In [26]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,3],[4,5],[6,7]])
print('x=' + str(x))
print('y=' + str(y))

x=[[1 2 3]
 [4 5 6]]
y=[[2 3]
 [4 5]
 [6 7]]


In [27]:
print(x.dot(y))   # 행렬 곱연산

[[28 34]
 [64 79]]


In [28]:
print('x='+str(x))
print("y'=" + str(y.transpose()))
print("x*y'= "+str(x*y.transpose()))   # 원소 곱 연산

x=[[1 2 3]
 [4 5 6]]
y'=[[2 4 6]
 [3 5 7]]
x*y'= [[ 2  8 18]
 [12 25 42]]


In [29]:
y = np.array([[2,3],[4,5],[6,7]])
print(y)
z = y.transpose()
print(z)
y[0,0] = 100;
print(y)
print(z)
#Transpose도 메모리 주소를 복사한다.

[[2 3]
 [4 5]
 [6 7]]
[[2 4 6]
 [3 5 7]]
[[100   3]
 [  4   5]
 [  6   7]]
[[100   4   6]
 [  3   5   7]]


In [30]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print('x='+str(x))
print('y='+str(y))
print(x*y)

x=[[1 2]
 [3 4]]
y=[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]


In [31]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print('x='+str(x))
print('y='+str(y))

x=[[1 2]
 [3 4]]
y=[[5 6]
 [7 8]]


In [32]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [33]:
# Slicing

In [34]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
print(x[1:3])

[1 2]


In [36]:
print(x[:4])
print(x[0:4])

[0 1 2 3]
[0 1 2 3]


In [37]:
print(x[3:])
print(x[3:x.size])

[3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]


In [38]:
print(x[3:8:2])    # 인덱스 3~8까지 2개 간격으로 출력
print(x[3:8:1])    # 인덱스 3~8까지 1개 간격으로 출력
print(x[3::1])     # 인덱스 3에서 끝까지 1개 간격으로 출력
print(x[3::2])     # 인덱스 3에서 끝까지 2개 간격으로 출력
print(x[::2])      # 인덱스 처음에서 끝까지 2개 간격으로 출력 
print(x[::-1])     # 인덱스 끝에서 처음까지 역순으로 출력
print(x[8:3:-1])   # 인덱스 8에서 3까지 역순으로 출력

[3 5 7]
[3 4 5 6 7]
[3 4 5 6 7 8 9]
[3 5 7 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]
[8 7 6 5 4]


In [44]:
x = np.array([1,6,21,1,5,2,13])
print(x)
b = x>3
print(b)
print(type(b))
print(x[b])
print(x[x>3])

print(x[[0 ,1,1,0, 1, False, True]])


x[x>3] = 100
print(x)

[ 1  6 21  1  5  2 13]
[False  True  True False  True False  True]
<class 'numpy.ndarray'>
[ 6 21  5 13]
[ 6 21  5 13]
[1 6 6 1 6 1 6]
[  1 100 100   1 100   2 100]


<class 'numpy.ndarray'>


In [41]:
def my_func1() :
    print('Hi! This is my first function.')
my_func1()

Hi! This is my first function.


In [159]:
def my_add(a,b) :
    c = a+b
    return c
my_add(2,10)

12

In [162]:
def my_func3(D):
    m = np.mean(D)  # 평균
    s = np.std(D)   # 표준 편차
    return m,s
data = np.random.randn(200)
data_mean , data_std = my_func3(data)
print('Mean:{0:3.2f}, std:{1:3.2f}'.format(data_mean,data_std))


Mean:0.07, std:1.03


In [166]:
data = np.random.randn(5)
print(data)
np.save('datafile.npy',data)
data=[]
print(data)
data = np.load('datafile.npy')
print(data)

[ 0.05778115 -0.1839554  -0.13064307  0.1197248   0.69595692]
[]
[ 0.05778115 -0.1839554  -0.13064307  0.1197248   0.69595692]


In [170]:
data1 =np.array([1,2,3])
data2 = np.array([10,20,30])
np.savez('datafile2.npz',data1=data1,data2=data2)
data1 = []
data2 = []
outfile = np.load('datafile2.npz')
print(outfile.files)
data1 = outfile['data1']
data2 = outfile['data2']
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]


In [50]:
data1 =np.array([1,2,3])
data2 = np.array([10,20,30])
np.savez('datafile2.npz',data1,data2)
data1 = []
data2 = []
outfile = np.load('datafile2.npz')
print(outfile.files)
data1 = outfile['arr_0']
data2 = outfile['arr_1']
print(data1)
print(data2)

['arr_0', 'arr_1']
[1 2 3]
[10 20 30]


In [171]:
x1 = np.arange(0,10,2)   # 0부터 10까지 2간격으로   0<= x1 <10
print(x1)

[0 2 4 6 8]


In [179]:
x2 = np.linspace(0,10,10)   # 0부터 10까지 동일한 간격으로 10개의 데이터 생성
print(x2)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
